'use client'

import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, Clock3, Filter, Inbox, MessageCircle, RefreshCw, Search, SlidersHorizontal, UserRound } from 'lucide-react'
import { PriorityPill, PageHeader, StatusPill, SupportShell, EmptyState } from '@/components/support-shell'

type Ticket = { id: string; reference_number: string; requester_name: string; requester_email: string; subject: string; description: string; category: string; urgency: string; status: string; ai_summary: string | null; ai_sentiment: string | null; ai_suggested_priority: string | null; ai_next_steps: string[]; created_at: string }
const tabs = ['All', 'Open', 'In Progress', 'Resolved']

export default function Dashboard() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [query, setQuery] = useState(''); const [tab, setTab] = useState('All'); const [selected, setSelected] = useState<Ticket | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [updating, setUpdating] = useState(false)
  async function load() { setLoading(true); setError(''); try { const res = await fetch('/api/tickets', { cache: 'no-store' }); if (!res.ok) throw new Error(); const data = await res.json(); setTickets(data.tickets ?? []) } catch { setError('We could not load the queue. Try refreshing the page.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const visible = useMemo(() => tickets.filter((ticket) => { const text = `${ticket.subject} ${ticket.requester_name} ${ticket.reference_number} ${ticket.category}`.toLowerCase(); return (tab === 'All' || ticket.status === tab) && text.includes(query.toLowerCase()) }), [tickets, tab, query])
  async function updateStatus(status: string) { if (!selected) return; const previous = selected; const next = { ...selected, status }; setSelected(next); setTickets((items) => items.map((item) => item.id === selected.id ? next : item)); setUpdating(true); try { const res = await fetch('/api/tickets', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: selected.id, status }) }); if (!res.ok) throw new Error() } catch { setSelected(previous); setTickets((items) => items.map((item) => item.id === previous.id ? previous : item)); setError('That update did not save. Please try again.') } finally { setUpdating(false) } }
  const count = (status: string) => tickets.filter((t) => t.status === status).length
  return <SupportShell><section className="px-4 py-7 sm:px-6 lg:px-8 lg:py-9"><PageHeader eyebrow="Support operations" title="Inbox" description="A clear, shared view of every customer request." action={<button onClick={load} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-border bg-card px-4 text-sm font-semibold hover:border-primary hover:text-primary"><RefreshCw size={16} className={loading ? 'animate-spin' : ''} /> Refresh</button>} />
    <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Inbox} label="Open" value={count('Open')} tone="primary" /><Stat icon={Clock3} label="In progress" value={count('In Progress')} tone="amber" /><Stat icon={MessageCircle} label="AI responded" value={tickets.filter((t) => t.ai_summary).length} tone="blue" /><Stat icon={CheckCircle2} label="Resolved" value={count('Resolved')} tone="green" /></div>
    <div className="mt-8 rounded-2xl border border-border bg-card shadow-sm"><div className="flex flex-col gap-4 border-b border-border p-4 sm:p-5 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold">Ticket queue</h2><p className="mt-1 text-xs text-muted-foreground">{visible.length} request{visible.length === 1 ? '' : 's'} in this view</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search className="absolute left-3 top-3 text-muted-foreground" size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-11 w-full rounded-xl border border-input bg-background pl-9 pr-3 text-sm outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 sm:w-64" placeholder="Search tickets" aria-label="Search tickets" /></label><button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-border px-3 text-sm font-semibold hover:bg-muted"><SlidersHorizontal size={16} /> Filters</button></div></div><div className="flex gap-1 overflow-x-auto border-b border-border px-4 pt-3 sm:px-5">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`min-h-11 whitespace-nowrap border-b-2 px-3 text-sm font-semibold ${tab === item ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}>{item}{item !== 'All' && <span className="ml-2 text-xs">{count(item)}</span>}</button>)}</div>{error && <div className="m-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-border text-[11px] uppercase tracking-widest text-muted-foreground"><th className="px-5 py-4">Request</th><th className="px-4 py-4">Category</th><th className="px-4 py-4">Priority</th><th className="px-4 py-4">Status</th><th className="px-5 py-4">Updated</th></tr></thead><tbody>{loading ? <LoadingRows /> : visible.length === 0 ? <tr><td colSpan={5}><EmptyState title="No tickets found" text="Try changing your search or status filter." /></td></tr> : visible.map((ticket) => <tr tabIndex={0} key={ticket.id} onClick={() => setSelected(ticket)} onKeyDown={(e) => e.key === 'Enter' && setSelected(ticket)} className="cursor-pointer border-b border-border last:border-0 hover:bg-muted/50 focus:bg-muted/50 focus:outline-none"><td className="px-5 py-4"><TicketIdentity ticket={ticket} /></td><td className="px-4 py-4 text-sm text-muted-foreground">{ticket.category}</td><td className="px-4 py-4"><PriorityPill value={ticket.ai_suggested_priority || ticket.urgency} /></td><td className="px-4 py-4"><StatusPill status={ticket.status} /></td><td className="px-5 py-4 text-xs text-muted-foreground">{new Date(ticket.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>
      <div className="divide-y divide-border md:hidden">{loading ? <div className="p-5 text-sm text-muted-foreground">Loading your queue...</div> : visible.length === 0 ? <EmptyState title="No tickets found" text="Try changing your search or status filter." /> : visible.map((ticket) => <button key={ticket.id} onClick={() => setSelected(ticket)} className="block min-h-28 w-full p-4 text-left hover:bg-muted/50"><TicketIdentity ticket={ticket} /><div className="mt-3 flex items-center gap-3"><StatusPill status={ticket.status} /><PriorityPill value={ticket.ai_suggested_priority || ticket.urgency} /><span className="ml-auto text-xs text-muted-foreground">{ticket.category}</span></div></button>)}</div>
    </div></section>{selected && <TicketDetail ticket={selected} close={() => setSelected(null)} updateStatus={updateStatus} updating={updating} />}</SupportShell>
}
function Stat({ icon: Icon, label, value, tone }: { icon: typeof Inbox; label: string; value: number; tone: string }) { return <div className="rounded-2xl border border-border bg-card p-4 shadow-sm sm:p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p></div><span className={`grid size-10 place-items-center rounded-xl ${tone === 'green' ? 'bg-emerald-50 text-emerald-700' : tone === 'amber' ? 'bg-amber-50 text-amber-700' : 'bg-primary/10 text-primary'}`}><Icon size={19} /></span></div><p className="mt-4 text-xs text-muted-foreground">Compared with last week</p></div> }
function TicketIdentity({ ticket }: { ticket: Ticket }) { return <div className="flex items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><UserRound size={17} /></span><div className="min-w-0"><p className="truncate text-sm font-semibold">{ticket.subject}</p><p className="mt-1 truncate text-xs text-muted-foreground">{ticket.reference_number} · {ticket.requester_name}</p></div></div> }
function LoadingRows() { return <>{[1, 2, 3].map((i) => <tr key={i}><td colSpan={5} className="px-5 py-5"><div className="h-10 animate-pulse rounded-lg bg-muted" /></td></tr>)}</> }
function TicketDetail({ ticket, close, updateStatus, updating }: { ticket: Ticket; close: () => void; updateStatus: (status: string) => void; updating: boolean }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-foreground/25 sm:items-center sm:p-5" onClick={close}><article className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl border border-border bg-card p-5 shadow-2xl sm:rounded-3xl sm:p-7" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">{ticket.reference_number}</p><h2 className="mt-2 text-xl font-semibold tracking-tight">{ticket.subject}</h2><p className="mt-2 text-sm text-muted-foreground">{ticket.requester_name} · {ticket.requester_email}</p></div><button onClick={close} className="grid size-11 place-items-center rounded-xl hover:bg-muted" aria-label="Close ticket">×</button></div><div className="mt-6 grid gap-3 rounded-2xl bg-muted p-4 sm:grid-cols-3"><p className="text-sm"><span className="text-muted-foreground">Category</span><br /><strong>{ticket.category}</strong></p><p className="text-sm"><span className="text-muted-foreground">Urgency</span><br /><strong>{ticket.urgency}</strong></p><p className="text-sm"><span className="text-muted-foreground">Received</span><br /><strong>{new Date(ticket.created_at).toLocaleDateString()}</strong></p></div><div className="mt-7"><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Conversation</p><div className="mt-3 rounded-2xl border border-border p-4 text-sm leading-7">{ticket.description}</div></div>{ticket.ai_summary && <div className="mt-5 rounded-2xl border border-primary/20 bg-primary/5 p-4"><p className="text-xs font-bold uppercase tracking-widest text-primary">Suggested brief</p><p className="mt-2 text-sm leading-6">{ticket.ai_summary}</p></div>}<div className="mt-7 flex flex-wrap gap-2"><span className="mr-auto self-center text-sm font-semibold">Move ticket to</span>{['Open', 'In Progress', 'Resolved'].map((status) => <button key={status} disabled={updating} onClick={() => updateStatus(status)} className={`min-h-11 rounded-xl px-4 text-sm font-semibold ${ticket.status === status ? 'bg-primary text-primary-foreground' : 'border border-border hover:border-primary hover:text-primary'}`}>{status}</button>)}</div></article></div> }
